name: Github Page Deploy

on:
  push:
    branches: main
    paths-ignore:
      - "**.md"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
        
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build --production
        
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build